export const INITIAL_FETCH = "INITIAL_FETCH";
export const SELECT_PERSON = "SELECT_PERSON";
export const NONE_SELECTED = "NONE_SELECTED";
export const CREATE_NEW_CONTACT = "CREATE_NEW_CONTACT";

export const FORM_UPDATE = "FORM_UPDATE";
